src/features/orders/orderAPI.ts
I noticed when looking over request code for aaaaaaaaaa's maker bot that if any server returns an error for an order, the entire `requestOrder` function would reject.
I've changed the code to use `Promise.allSettled` instead, then to filter out error responses, and return only valid orders.
Note that in the event all servers return an error, the promise returned by this function **will still resolve**, but with an empty array. I'm not sure whether this is desirable, or if we should check for this case and reject (my preference is empty array).
---
Brief typescript explanation (because it confused me at first):
- `Promise.allSettled` returns `PromiseSettledResult<T>`s which have just a `status` property  `("fulfilled"|"rejected")`. 
-`PromiseFulfilledResult<T>` extends this with `value: T` …
=> Use `Promise.allSettled` in `requestOrder`

src/features/orders/Orders.tsx, src/features/orders/ordersSlice.spec.ts, src/features/orders/ordersSlice.ts
Closes #60 
- Changes `selectOrder` which previously selected the first order, to `selectBestOrder` which selects based on either receiving the most `signerToken` in the case of a `signerSideOrder` or sending the least `senderToken` in the case of a `senderSideOrder`
Have skipped the case where two orders are exactly the same in quantities as I feel this is unlikely to happen.
=> Select best order + test

public/locales/en/orders.json, src/components/TokenSelect/TokenSelect.tsx, src/features/orders/Orders.tsx
New pr 👯‍♂️ 
Added feature to enable red text whenever senderAmount is greater than the current balance. 
Features:
1. Input text turns red if senderAmount is greater than the current balance.
2. Request button texts changes to have 3 options: "Enter an Amount" (initial), "Request" (sufficient), "Insufficient ___ balance" (insufficient)
3. Added `handleTokenAmountChange` function to handle non numeric and period values into input.
4. new AmountStatus type in `TokenSelect.tsx`
Some discussion points:
1. Do all tokens have 18 decimal denominations? I assumed they do, so calculate balance and current senderAmount based off of that.
2. Should a user still be able to request a quote if they don't have enough balance?
3. Is AmountStatus a good name for the status of the senderAmount? (I'm …
=> Issue 55: Add visual indicator if sender amount is greater than current balance

src/components/SwapWidget/SwapWidget.tsx, src/features/wallet/Wallet.tsx, src/features/wallet/walletSlice.ts
Per an earlier conversation with @gpxl-dev, I made the following changes to wire up the connect wallet button in `SwapWidget`:
1. Updated redux state to allow setting a `providerName`
2. Added local state to toggle between loading modes for the connect wallet button
3. Added a `useEffect` inside `Wallet.tsx` to set `provider` and `connector` so that the other `useEffect` that fetches balances etc. is triggered.
4. Updated `onProviderSelected` logic for the `WalletList` component
Points for discussion:
1. It was discussed adding a `connecting` state to the wallet redux state in the event we have multiple connect wallet buttons, I had started to add that in but stopped because 
a. I wasn't sure if we would even need local loading state anymore (in favor of the redux state).
b. I supposed we …
=> SwapWidget Wallet Connection

package.json, public/locales/en/balances.json, src/app/store.ts, src/components/SwapWidget/SwapWidget.tsx, src/components/TokenSelection/TokenSelection.stories.tsx, src/components/TokenSelection/TokenSelection.tsx, src/components/TokenSelection/subcomponents/InactiveTokensList/InactiveTokensList.tsx, src/components/TokenSelection/subcomponents/TokenImportButton/TokenImportButton.styles.tsx, src/components/TokenSelection/subcomponents/TokenImportButton/TokenImportButton.tsx, src/components/WalletButton/subcomponents/TransactionLink/TransactionLink.tsx, src/features/registry/registryAPI.tsx, src/features/registry/registryDeploys.d.ts, src/features/registry/registrySlice.ts, src/features/transactions/Transactions.tsx, src/features/wallet/Wallet.tsx, yarn.lock
- Adds a `registry` slice to state which contains a list of the tokens supported by each staker (maker), as well as a list of all tokens supported across all makers.
- Updates the token selection screen to prevent importing unsupported tokens to a user's active tokens list
- Upgrades @airswap/protocols
This branch probably has a non-ideal UX, but preventing active token import is the fastest & most feasible way to implement pre-alpha.
Screenshot:
Closes #126
=> Restrict tokens to those in registry

src/components/SwapWidget/SwapWidget.tsx, src/features/orders/ordersSlice.ts
Previously rejecting a metamask signature request would essentially be ignored and incorrectly show the transaction submitted screen.
Note for anyone reading this who is new to redux toolkit - I had wrongly assumed that `await dispatch(someThunkGeneratingAction)` would throw if the thunk rejected. It doesn't - you need to use `unwrapResult`, like this:
```javascript
try {
const result = await dispatch(someThunkGeneratingAction)
await unwrapResult(result);
// do success specific stuff.
} catch (e) {
// you would never get here if you didn't await the unwrap.
}
```
=> Don't show submitted screen if signature rejected

src/features/metadata/metadataApi.ts, src/features/metadata/metadataSlice.ts, src/features/registry/registrySlice.ts, src/features/wallet/Wallet.tsx
Fixes #168
- Waits for tokenLists and supportedTokens to be fetched
- Determines if any supportedTokens don't have TokenInfo from tokenlist
- Fetches missing tokenInfo using `scrapeToken` from `@airswap/metadata`
- Caches metadata in localStorage (`airswap/metadataCache/[chainId]`) and doesn't requests subsequently.
Note that localStorage is automatically freed up on load if either metadata or supportedTokens change such that some previously stored TokenInfo is now extraneous.
At time of PR there are 6 tokens supported in the registry that are not in our Token lists - you can use one of these to test:
```text
0x83f798e925bcd4017eb265844fddabb448f1707d
0x16de59092dae5ccf4a1e6439d611fd0653f0bd01
0xbc5cef436eadacadfa8dafb63088f09f21dea7e9
0xc2cb1040220768554cf699b0d863a3cd4324ce32 …
```
=> Use on chain data if tokenLists are missing tokens

package.json, src/features/metadata/metadataApi.ts, src/features/metadata/metadataSlice.ts, yarn.lock
Closes #51 
Updated `@airswap/metadata` package to `0.3.6`. In the new package, `fetchTokens` returns `{errors: [], tokens:[]}}`. Updates were made to parts of the code where `fetchTokens` was used to accommodate for the new return shape. Return errors will be handled in a later ticket.
=> Update metadata package

public/locales/en/common.json, src/App.tsx, src/components/BookmarkWarning/BookmarkWarning.styles.tsx, src/components/BookmarkWarning/BookmarkWarning.tsx, src/components/Icon/Icon.tsx, src/components/Icon/icons/IconX.tsx, src/components/Icon/icons/index.ts, src/components/Page/Page.styles.tsx, src/components/Page/Page.tsx, src/components/PageLoader/PageLoader.tsx, src/components/SiteLogo/SiteLogo.tsx, src/features/userSettings/helpers/getInitialBookmarkWarning.ts, src/features/userSettings/userSettingsSlice.ts
Added a bookmark warning div that displays a bookmark warning as shown in the Figma design.
The feature is implemented by pushing the content down by 2 rem units. When displayed, the total page height is shrinked by the same amount to avoid showing a scrollbar. Tested in Firefox and Chrome.
=> adds a bookmark warning to the top of the app

src/components/SwapWidget/SwapWidget.tsx, src/features/orders/ordersSlice.ts
@codyenokida - I looked into how to get the revert reason from a failed transaction. Your google fu may be stronger than mine, but I came to the conclusion there is no reliable way to do it at present for a number of reasons.
Added to the fact we don't actually display the "reason" for a revert anywhere currently, I hard coded "transaction reverted" as the reason. Let me know if you think there's a better option.
The other changes were straightforward.
Fixes #227
=> Fix order api types

public/locales/en/orders.json, src/components/Page/Page.tsx, src/components/SwapWidget/SwapWidget.styles.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/features/orders/Orders.tsx, src/features/wallet/Wallet.tsx
Fixes #295 
- Adds secondary button functionality to `ActionButtons`, and adds secondary "Track" button on swap complete
- Fixes margins on huge ticks to fit with designs
- Extracts transaction open state to page level so that `SwapWidget` can open the drawer.
- Fixes wording
- Removes extraneous `orders.tsx`
=> Update "swap complete" screen

src/components/TransactionsTab/TransactionsTab.tsx
Not all transactions have a hash, so those end up key-less (with an error in the console). This fix concats the hash with a nonce so that they'll have a unique key. Vice versa, not all transactions have a nonce, so you can't rely on that either. But they all have either one.
=> modifies transaction key

src/components/SwapWidget/subcomponents/SwapInputs/SwapInputs.tsx
This regex strips all leading zeros and replaces it with a single one.
I've checked with a few dexes and some allows multiple leading zeros, some no zeroes at all before the dot. So I guess this strikes a balance between the two approaches. You're still allowed to have one leading zero, so you can write `01234.01234`. 
Closes #334
=> replaces leading zeros with a single zero

public/locales/en/validatorErrors.json, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.tsx, src/contexts/lastLook/LastLook.tsx, src/features/pricing/pricingApi.ts
Fixes #362 
The issues:
1. When last look orders were being generated, the entered amount was being used for the `signerAmount`, instead of `signerAmount + fee`. This would result in failed swaps if a user's max balance was used.
2. Fee calculations were using fees that were one order of magnitude too big (0.7% instead of 0.07%). This resulted in quote amounts that were too small.
To reproduce the issues (before checking out this branch):
1. Try to swap your max WETH for DAI on rinkeby. You'll hit the validator error saying you have insufficient balance (note the text is wrong!)
2. Swap less than your max balance and look at the actual amounts sent and received.
To verify this works, checkout the branch and swap your max WETH balance for DAI on rinkeby. You should be left with exactly …
=> Fix fee calculations

src/components/SocialButtons/SocialButtons.styles.tsx, src/components/SocialButtons/SocialButtons.tsx
- Fixes link nested in link (caused console error in best case)
- Removes divider that was appearing on hovering even if there were no locales
- Adds a black background on hover to cover the case that the widget is being overlapped by the locales list
Doesn't address the active state when clicking a link (which I think is pretty minor) but otherwise closes #350 - @piersss if you have a good way to deal with the focus problem then please feel free to add it to this PR.
Finally mobile experience needs work here as it's hard to get to the French twitter - not sure of an easy way around this - ideally want to tap once to open the locales list on mobile, but maintain behaviour on desktop.
=> Social links changes

public/locales/en/balances.json, public/locales/en/common.json, src/App.tsx, src/components/Page/Page.tsx, src/components/SwapWidget/InfoSection.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/constants/supportedWalletProviders.ts, src/features/balances/balancesSlice.ts
Closes #349 
In rare cases, the call to fetch ERC20 token allowances for our contracts may fail. This is a failure that could cause a user to waste funds on gas re-approving tokens that are already approved.
This PR provides an interim fix by not allowing the user to proceed following a failed allowances request. The SwapWidget becomes disabled, and the Info text informs the user that fetching token allowances has failed, and that they'll need to reload the page. The action button becomes a "Reload Page" button.
The best way to test this is to short circuit the allowance check by throwing an error on line 77 of `balancesSlice.tsx`.
As a bonus, this PR also fixes the fact that balances and allowances are requested three times on every page load because new `connector` and `provider` …
=> Prevent showing approve button unneccessarily

src/assets/weth9.abi.json, src/components/Toasts/ToastController.tsx, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.tsx, src/constants/Weth9.ts, src/contexts/lastLook/LastLook.tsx, src/features/balances/balancesSlice.ts, src/features/transactions/swapEventSubscriber.ts, src/features/transactions/transactionsSlice.ts, src/features/transactions/wrapEventSubscriber.ts, src/features/wallet/Wallet.tsx
Add listeners for Deposit and Withdrawal events from WETH contract to catch ETH/WETH "swaps"
Events are emitted on` ETH->WETH` and `WETH<-ETH` (and only these are the ones I've tested).
Closes #379
=> Adding listener for deposit and withdrawals

src/constants/supportedWalletProviders.ts
The code assigned WalletConnect to Metamask but returned WalletConnect. After changing this, the walletconnect QR code and login flow started. 
closes #425
=> Fix for WalletConnect

src/components/TransactionsTab/subcomponents/AnimatedWalletTransaction/AnimatedWalletTransaction.tsx
Fixes #455 
Only recent transactions (within half an hour) animate in with this fix:
https://user-images.githubusercontent.com/86911296/147755972-cec25702-4fb6-4d27-abec-cb67836bcad9.mov
=> Fixed small wallet transaction animation bug

src/components/SwapWidget/SwapWidget.tsx, src/constants/addressAliases.ts, src/hooks/useAppRouteParams.ts
Fixes #506 
I used constants/nativeCurrency.ts to get the name of native token. For example, an url could be:
- `swap/eth/0x5592ec0cfb4dbc12d3ab100b257153436a1f0fea`
- `swap/0xc778417e063141139fce010982780140aa0cd5ab/matic`
=> 506: Replace 0x000..000 with native token in url

src/components/ProgressBar/ProgressBar.styles.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/ProgressBar/helpers/getProgressBarAnimationProps.spec.ts, src/components/ProgressBar/helpers/getProgressBarAnimationProps.ts
Fixes #513 
There were 2 problems:
- Logic for calculating time left and progress was not working.
- Framer-motion not reacting well to restarting animations
So I rewrote logic and added helper with some tests and did animations with simple css.
=> 513: Added getProgressBarAnimationProps helper and tests

package.json, src/constants/configParams.ts, src/features/orders/orderApi.ts, src/features/orders/ordersSlice.spec.ts, src/features/orders/ordersSlice.ts, yarn.lock
Fixes #521 
Copied from my response in the issue itself:
> I've checked out the code quite extensively and the only way I can see this could happen is a kind of race condition:
>
> - Orders are re-requested when we get to within 1M of the exiry
> - User clicks "new swap"
> - Response from makers comes in and populates the orders state before the user has a chance to do anything. Once there's an order in the orders state the SwapWidget changes its behaviour and could cause the state displayed in the screenshot.
>
> To mitigate this I'll do a couple of things:
>
> - Cancel the re-request when take is successfully fulfilled (it's currently only being cancelled when we click "new swap")
> - Don't update the orders slice with orders if its state wasn't "requesting".
Note that I couldn't …
=> Fix potential race condition causing bad UI state

src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/SwapInputs/SwapInputs.tsx
- `side` in `SwapInputs` only updates token names, amounts now switch with `userIsMakerOfSwap` truthiness
=> Fixes #638 token amount bug

.env, .github/workflows/deploy.yml, package.json, src/constants/supportedWalletProviders.ts
- tested WalletConnect using rainbow and goerli
- connected wallet, sent read-only transactions
- approved and signed make order in OTC swap
- WalletConnect supports Mainnet and Goerli with this change
=> WalletConnect fix

public/locales/en/translation.json, src/components/MyOrdersWidget/helpers/index.ts, src/components/MyOrdersWidget/subcomponents/MyOrdersList/MyOrdersList.styles.tsx, src/components/MyOrdersWidget/subcomponents/MyOrdersList/MyOrdersList.tsx, src/components/MyOrdersWidget/subcomponents/Order/Order.styles.tsx, src/components/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/hooks/useOrderStatus.tsx, src/components/OrderDetailWidget/subcomponents/OrderStatusInfo/OrderStatusInfo.tsx, src/features/takeOtc/takeOtcActions.ts, src/types/orderStatus.ts
Fixes #652
Also gave canceled orders a red indicator that has "Canceled" tooltip.
=> 652: Added tooltip to order status indicator

public/locales/en/translation.json, src/components/InformationModals/subcomponents/FeeModal/FeeModal.styles.tsx, src/components/InformationModals/subcomponents/FeeModal/FeeModal.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/subcomponents/OrderRecipientInfo/OrderRecipientInfo.tsx, src/components/Toasts/CopyToast.tsx, src/components/Toasts/ToastController.tsx, src/components/TransactionsTab/subcomponents/CopyAddressButton/CopyAdressButton.tsx, src/helpers/writeTextToClipboard.ts, src/styled-components/Pill/Pill.tsx
Fixes #668 
- `LargePillButtonStyled` adjusted to match border radius
- `CopyToast` created and notified on copy success
- fee modal cleaned, `ScrollableContainer` alters some styling so removed until needed
- no fix on vertical alignment, this may be a seperate issue as it appears all of 2xASTs buttons were misaligned, but not recreated on my end.
=> Fixes #668 fee modal and info buttons

public/locales/en/translation.json, src/components/ErrorList/helpers/index.ts, src/components/MakeWidget/MakeWidget.tsx, src/components/MakeWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/SwapInputs/SwapInputs.styles.tsx, src/components/SwapInputs/SwapInputs.tsx, src/components/SwapInputs/hooks/useErrorTranslation.ts, src/components/TokenSelect/TokenSelect.tsx, src/components/TokenSelect/subcomponents/TokenSelectFocusBorder/TokenSelectFocusBorder.styles.tsx, src/components/TokenSelect/subcomponents/TokenSelectFocusBorder/TokenSelectFocusBorder.tsx, src/errors/appError.ts, src/errors/numericFaultError.ts, src/errors/transformUnknownErrorToAppError.ts, src/features/makeOtc/makeOtcActions.ts, src/helpers/toAtomicString.ts, src/hooks/useStringToSignificantDecimals.ts, src/hooks/useTokenAmountError.ts
Fixes #678 
`toAtomicString` throws 2 different errors when passing really small numbers (`invalid decimal value` or `underflow`). Put a wrapper function around it to properly transform these errors to AppError.
This AppError gets passed to SwapInputs and to show error state and tooltip, both errors translate to "Amount is too small".
Also learned a new word: [arithmetic underflow](https://en.wikipedia.org/wiki/Arithmetic_underflow).
https://user-images.githubusercontent.com/86911296/204320491-6e9b7993-87cd-4b30-94b4-9def8ee329b8.mov
=> 678: Limit decimal places on number inputs to token decimal places

src/components/TokenSelect/helpers/index.ts
If a token does not exist on the switched chain, it becomes undefined. 
This case was treated as the existing one for the null check.
=> TypeError when switching chains

src/components/MakeWidget/MakeWidget.tsx, src/components/MakeWidget/subcomponents/RateField/RateField.tsx
Fixes #707 
- rate field token state now handled via boolean rather than array to update correctly
- changes in tokens or amounts will reflect accurately in Rate Field state
- changes will reset to default maker token = [ rate ] taker token state layout
=> Fixes #707, Rate Field Token switch

src/components/MakeWidget/MakeWidget.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/WalletButton/WalletButton.tsx, src/components/WalletButton/helpers/index.ts, src/components/WalletButton/subcomponents/WalletAddress/WalletAddress.tsx, src/features/balances/balancesSlice.ts, src/features/metadata/metadataSlice.ts, src/features/transactions/transactionsSlice.ts, src/features/wallet/Wallet.tsx
Fixes #725 
- Improved cleanup of store when switching / disconnecting wallet
- TokenList will close when disconnected
- Fixed wallet button indicator when wallet is not connected.
=> 725: Improved clearing store when switching between wallets

src/components/Dropdown/Dropdown.styles.tsx, src/components/Dropdown/Dropdown.tsx, src/components/MakeWidget/MakeWidget.styles.tsx, src/components/MakeWidget/MakeWidget.tsx, src/components/MakeWidget/helpers/index.ts, src/components/MakeWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/MakeWidget/subcomponents/AddressInput/AddressInput.styles.tsx, src/components/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/SwapInputs/subcomponents/Tooltip/Tooltip.styles.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/TokenSelect/TokenSelect.tsx, src/style/themes.ts, src/styled-components/Modal/Modal.tsx
Fixes #774 
Expiry dropdown
Counterparty Wallets popover
Make screen
My Orders
Swap
=> 774: Added various styling fixes

public/locales/en/translation.json, src/components/MakeWidget/MakeWidget.tsx, src/components/SwapWidget/SwapWidget.tsx, src/features/balances/balancesSlice.ts, src/features/gasCost/gasCostApi.ts, src/features/metadata/metadataSlice.ts, src/features/orders/ordersSlice.ts, src/helpers/getWethAddress.ts, src/hooks/useApprovalPending.ts, src/hooks/useNativeWrappedToken.ts, src/hooks/useShouldDepositNativeTokenAmount.ts, src/hooks/useShouldDepositNativeTokenAmountInfo.ts, src/hooks/useSufficientAllowance.ts, src/hooks/useSwapType.ts
Fixes #793 
Fixes wrapping ETH for Maker and Taker side. Will do last fixes and testing later today.
- WETH.getAddress() returns address that's not lower case. So it failed to match the correct address in several places.
- Allowances and balances only accounting for active tokens. It will now automatically add WETH and other custom tokens.
https://github.com/airswap/airswap-web/assets/86911296/92ce9598-a4fb-4477-828a-d274ba6a1a0a
https://github.com/airswap/airswap-web/assets/86911296/468c4c81-b4f7-4fae-990b-572681f9993a
=> 793: Added fix for wrapping native token and missing balances

src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/subcomponents/CopyLinkButton/CopyLinkButton.styles.tsx, src/components/OrderDetailWidget/subcomponents/CopyLinkButton/CopyLinkButton.tsx, src/components/OrderDetailWidget/subcomponents/InfoButtons/InfoButtons.styles.tsx, src/components/OrderDetailWidget/subcomponents/InfoButtons/InfoButtons.tsx
Fixes #728 
When copy to clipboard fails the copy button is replaced with a div element that's automatically selected so the user can manually copy the link.
https://github.com/airswap/airswap-web/assets/86911296/ed5e3eaf-cee1-4671-bb51-3709348ddc86
=> 728: Added fallback when copy to clipboard fails

src/components/SwapWidget/SwapWidget.tsx, src/features/orders/orderApi.ts, src/hooks/useSwapType.ts
Fixes #834 
https://github.com/airswap/airswap-web/assets/86911296/5984bcdb-e575-4677-9701-ef9010e36cd0
https://goerli.etherscan.io/tx/0x1ecde9aa417cdee6f33d0528dfecaa5070f74de2b2e0911241a9fa131e8ca267
Also fixed bug when swapping from ERC20 to ETH. Which is actually WETH, that's why we need to implement the review screen for RFQ later (#831).
=> 834: Fixed RFQ errors when swapping from and to native token

src/components/@widgets/MakeWidget/MakeWidget.tsx
This PR fixes [a problem an OTC maker was having](https://discord.com/channels/590643190281928738/599315389327081492/1147978174253236366) whereby they couldn't sign their order.
They have tried to enter a number of decimals that is unsupported by the tokens, so the parse is failing.
The UI does already have a check function for this `toMaxAllowedDecimalsNumberString`, but for some reason this function ignores numbers > 1.
I've updated the function & test.
=> Fix `toMaxAllowedDecimalsNumberString`

src/components/@widgets/OrderDetailWidget/OrderDetailWidget.tsx
Comparison was being made between lowercased and checksummed. Also changes to ADDRESS_ZERO in place of nativeCurrencyAddress to make it clear to the developer that the logic isn't related to the native currency.
=> Fixes an issue with specific takers on OTC

src/components/@reviewScreens/ApproveReview/ApproveReview.styles.tsx, src/components/@widgets/OrderDetailWidget/hooks/useFormattedTokenAmount.ts, src/components/TokenList/subcomponents/TokenImportButton/TokenImportButton.styles.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/styled-components/ReviewListItem/ReviewListItem.tsx
Fixes #879 
https://github.com/airswap/airswap-web/assets/86911296/b2a92804-901e-4775-a465-cad40a2c7dd4
=> 879: 𒐪𒐪𒐪𒐪𒐪

src/components/@reviewScreens/ApproveReview/ApproveReview.tsx, src/components/@reviewScreens/WrapReview/WrapReview.tsx, src/components/@widgets/MakeWidget/MakeWidget.tsx, src/components/@widgets/MakeWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/@widgets/OrderDetailWidget/OrderDetailWidget.tsx, src/components/@widgets/SwapWidget/SwapWidget.tsx
Fixes #853 
https://github.com/airswap/airswap-web/assets/86911296/cf2643ea-1f3e-4c3f-bfd5-6c83bd7e2638
Fixed for Make, Take and RFQ widget.
When clicking back from approve or wrap it takes you back to the start screen. Removed any loading state in start screen so user is free to go back to approve or wrap screen or change the query.
Resetting the query is not necessary I think but could still add that if necessary.
=> 853: Clicking "Back" during pending transaction should reset

package.json, src/components/@widgets/OrderDetailWidget/hooks/useSessionOrderTransaction.ts, src/components/@widgets/SwapWidget/SwapWidget.tsx, src/components/@widgets/SwapWidget/subcomponents/SwapWidgetHeader/SwapWidgetHeader.tsx, src/components/Toasts/ToastController.tsx, src/components/Toasts/TransactionToast.tsx, src/components/TransactionsTab/TransactionsTab.tsx, src/components/TransactionsTab/subcomponents/AnimatedWalletTransaction/AnimatedWalletTransaction.tsx, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.tsx, src/constants/configParams.ts, src/contexts/lastLook/LastLook.tsx, src/entities/FullSwapERC20Event/FullSwapERC20EventHelpers.ts, src/entities/SubmittedTransaction/SubmittedTransaction.ts, src/entities/SubmittedTransaction/SubmittedTransactionHelpers.ts, src/entities/SubmittedTransaction/SubmittedTransactionTransformers.ts, src/features/orders/ordersActions.ts, src/features/orders/ordersSlice.ts, src/features/transactions/hooks/useHistoricalTransactions.ts, src/features/transactions/hooks/useLatestExpiredTransaction.ts, src/features/transactions/transactionsActions.ts, src/features/transactions/transactionsHelpers.ts, src/features/transactions/transactionsHooks.ts, src/features/transactions/transactionsSlice.ts, src/features/transactions/transactionsUtils.ts, src/features/wallet/Wallet.tsx, src/hooks/useOrderTransaction.ts, src/hooks/useOrderTransactionLink.ts, yarn.lock
Fixes #891  
Expiry of LastLook transactions are now handled in the transactionHooks file.
Removed all logic for keeping track of expired transactions from store. This is considered bad practice, you should only store data in your store. Adding timeouts will create side effects and will make cleanup more complicated.
Added a SubmittedOrderUnderConsideration interface for LastLook orders that are submitted but not have a transaction hash yet and are sent for consideration to LastLook.
Removed the `last-look` and `request-for-quote` types. All orders are now the same, except when it has a `isLastLook=true`. Then the hash can be optional.
=> 891: Fix LastLook expired transactions

src/components/@widgets/SwapWidget/SwapWidget.tsx, src/components/@widgets/SwapWidget/hooks/useBestTradeOptionTransaction.ts, src/components/TransactionsTab/TransactionsTab.tsx, src/components/TransactionsTab/helpers/getWalletTransactionOrderText.ts, src/components/TransactionsTab/subcomponents/AnimatedWalletTransaction/AnimatedWalletTransaction.tsx, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.tsx, src/entities/SubmittedTransaction/SubmittedTransaction.ts, src/entities/SubmittedTransaction/SubmittedTransactionHelpers.ts, src/entities/SubmittedTransaction/SubmittedTransactionTransformers.ts, src/features/orders/ordersActions.ts, src/features/transactions/hooks/useHistoricalTransactions.ts, src/features/transactions/transactionsHelpers.ts, src/features/wallet/Wallet.tsx, src/helpers/getOrdersFromLogs.ts
Fixes #893 
- Completed orders now have a swap property with the FullSwapERC20.
- Added helpers for wallet transaction labels
=> 893: Add FullSwapERC20 to order transactions

src/components/Routes/Routes.tsx, src/components/TokenList/TokenList.tsx, src/features/balances/balancesApi.ts, src/features/balances/balancesHooks.ts, src/features/balances/balancesSlice.ts, src/features/orders/ordersActions.ts, src/features/transactions/transactionsHelpers.ts, src/features/transactions/transactionsHooks.ts, src/features/wallet/Wallet.tsx
Fixes #889 
Removed balance dispatches throughout the app and consolidated everything into balanceHooks.
Every time a transaction succeeds we update balances or allowances depending on the type of transaction.
=> 889: Consolidated balance handling in balances store

src/entities/OrderERC20/OrderERC20Service.ts, src/features/balances/balancesApi.ts, src/features/makeOtc/makeOtcActions.ts, src/features/metadata/metadataApi.ts, src/features/orders/ordersActions.ts, src/features/orders/ordersHelpers.ts, src/features/takeOtc/takeOtcActions.ts, src/features/transactions/hooks/useLatestApproveFromEvents.ts, src/features/transactions/hooks/useLatestCancelFromEvents.ts, src/features/transactions/hooks/useLatestSwapFromEvents.ts, src/features/transactions/hooks/useSwapLogs.ts, src/helpers/swapErc20.ts
=> 915: Revert swap contract to v4

index.js, package.json, yarn.lock
Hopefully this fixes gnosis not recognising https://airswap-web-dev.herokuapp.com as a gnosis safe app.
Fixes #908
=> 908: Added cors config to express server

src/features/registry/registryApi.ts
Fixes #997 
1. Get all stakers by calling `getStakersForProtocol` for `ProtocolIds.RequestForQuoteERC20` and `ProtocolIds.LastLookERC20`
2. Then call `getTokensForStaker` for each staker.
=> 997: Added fix to getStakerTokens
