airswap/airswap-web

src/components/Timer/Timer.stories.tsx
Bugfix that I saw that was breaking storybook timer component
=> added onTimerComplete to storybook component

public/locales/en/common.json, public/locales/en/wallet.json, src/components/Icon/Icon.tsx, src/components/TokenSelection/TokenSelection.stories.tsx, src/components/TokenSelection/TokenSelection.tsx, src/components/WalletButton/TransactionRow.styles.tsx, src/components/WalletButton/TransactionRow.tsx, src/components/WalletButton/WalletButton.spec.tsx, src/components/WalletButton/WalletButton.stories.tsx, src/components/WalletButton/WalletButton.styles.tsx, src/components/WalletButton/WalletButton.tsx, src/components/WalletButton/subcomponents/TransactionLink/TransactionLink.style.tsx, src/components/WalletButton/subcomponents/TransactionLink/TransactionLink.tsx, src/components/WalletButton/subcomponents/WalletTransaction/WalletTransaction.styles.tsx, src/components/WalletButton/subcomponents/WalletTransaction/WalletTransaction.tsx, src/components/WalletButton/subcomponents/WalletTransactionStatus/WalletTransactionStatus.tsx, src/features/metadata/metadataSlice.ts, src/features/metadata/metadataSubscriber.ts, src/features/orders/ordersSlice.ts, src/features/transactions/transactionsSlice.ts, src/features/wallet/Wallet.tsx, src/helpers/getTimeBetweenTwoDates.spec.ts, src/helpers/getTimeBetweenTwoDates.ts
Hi all!
PR to view recent transactions and view wallet status;
Features:
1. Expand transaction list from wallet widget
2. persist 3 most recent transactions
3. updated storybook (although it looks wonky on storybook)
4. added timestamp to all transactions (when loading, may need to remove from old transaction struct from localStorage)
5. new logic to metadata subscriber to fix bug that persisted transactions across wallet changes
6. updated styling to match figma
Some TODOs that may change in future PRs:
1. background color of widget (don't know the color for light mode.. probably will be the same as the side content bar, but that's tbd at the moment)
2. Fixed length of wallet widget?
Comments/feedback appreciated!
=> Wallet and Transaction Component 

public/locales/en/orders.json, src/components/Content/Introduction.tsx, src/components/Content/Organization.tsx, src/components/Content/Products.tsx, src/components/SwapWidget/InfoSection.tsx, src/components/SwapWidget/SwapWidget.styles.tsx, src/components/SwapWidget/SwapWidget.tsx
Added wallet prompt state in swap widget, added i18n text
- Added additional styling to center relevant text; hide button; change title for wallet prompt states
TODOS/Comments: refactor swap widget somehow?? The whole component is a mouthful tbh and not easy to navigate through
=> [Feature] - Wallet Prompt State

src/components/SwapWidget/SwapWidget.tsx, src/features/orders/orderAPI.ts
Fixes #169 and #170
Two pretty simple changes!
=> Implement order timeouts & handle no valid orders

src/components/TokenSelection/TokenSelection.tsx, src/components/TokenSelection/sort.spec.ts, src/components/TokenSelection/sort.ts, src/components/TokenSelection/subcomponents/InactiveTokensList/InactiveTokensList.tsx
Checked out other protocols to see a good optimized way to do this :) 
- filter based on symbol first
Some other unrelated issues:
- Uniswap token needs a placeholder
=> Added token sorting based on symbol first, then substring

src/App.tsx, src/components/Page/Page.tsx, src/components/SideBar/SideBar.styles.tsx, src/components/SideBar/SideBar.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/helpers/findTokenFromAndTokenToAddress.spec.ts, src/components/SwapWidget/helpers/findTokenFromAndTokenToAddress.ts, src/components/TokenSelect/TokenSelect.tsx, src/routes.ts
I think the default should be USDT -> WETH, but after the user selects a token, those should be saved to local storage and used as the new default. I can add that if you guys agree.
Edit: This ticket will be combined with #179
=> Added default tokens (USDT, WETH) to SwapWidget

src/components/WalletProviderList/WalletProviderList.styles.tsx, src/components/WalletProviderList/WalletProviderList.tsx
There was still some tailwind classes in there. Fixes #187
=> Fixed styling of WalletProviderList

public/locales/en/common.json, src/components/SwapWidget/SwapWidget.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/TokenSelect/TokenSelect.tsx
Closes #196 
Works but needs some styling/design changes.
- potentially account for much larger values in the input
- consider transitioning position of amount when entering / exiting read only mode (button will appear and disappear)
=> Max button (WIP)

public/locales/en/marketing.json, src/components/Page/Page.tsx, src/components/PageLoader/PageLoader.tsx, src/components/SwapWidget/SwapWidget.tsx
Closes #192 
- Changes first state text (use at own risk etc.)
- Removes sidebar and dark/light toggle temporarily
- Fixes a bug where switching from a token with a larger number of decimals to the token switched to caused a crash
=> Pre beta tweaks

src/components/TokenSelect/TokenSelect.styles.tsx
https://github.com/airswap/airswap-web/issues/202
=> Fixed firefox TokenSelect label text-align

public/locales/en/wallet.json, src/components/WalletButton/subcomponents/WalletTransaction/WalletTransaction.tsx, src/helpers/getTimeBetweenTwoDates.spec.ts, src/helpers/getTimeBetweenTwoDates.ts, yarn.lock
- Added and refactored tests to be able to support i18n language support or time ago
=> [Bugfix] Added Locale i18n support for time ago on transactions

src/components/Overlay/Overlay.styles.tsx, src/components/SettingsPopover/SettingsPopover.styles.tsx, src/components/TransactionsTab/TransactionsTab.styles.tsx, src/style/mixins.ts
- Added a style/mixins.ts file for reusable styles.
- Added ScrollBar mixin and added to multiple components
=> 265: Added mixin file with scrollbar styling

src/components/WidgetFrame/WidgetFrame.styles.tsx, src/components/WidgetFrame/WidgetFrame.tsx, src/style/styled.d.ts, src/style/themes.ts
- Blur implemented as per designs
- Added `shadows` key to theme, expect to use this in future for other similar effects
=> Replace animated background blur with static shadow

src/components/SwapWidget/SwapWidget.tsx
=> Fix ETH approval check

src/styled-components/Modal/Modal.tsx
=> Fix join modal size and position

public/locales/nb/wallet.json
=> more locale changes

src/contexts/lastLook/LastLook.tsx
Closes #322 
This was a memoization problem - the resize triggers the `useWindowSize` hook to update the state in `App.tsx` which in turn rerenders all of the child components, including the `LastLookProvider` which was recomputing the value passed to the context, and therefore triggering the hook to clear the state on chain change that required the `LastLook` context as a dependency because it needs it to disconnect from all servers.
=> Fix clearing app state on resize

src/components/WalletProviderList/WalletProviderList.styles.tsx
Removes uppercase transform to wallet provider text
Closes #297
=> removes uppercase

src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/subcomponents/SwapInputs/SwapInputs.styles.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/TokenSelect/TokenSelect.tsx
Fix for #303 (also tabindex for tabbing to input field)
=> Set mouse cursor to denied on input form when wallet not connected

public/locales/en/common.json, public/locales/nb/balances.json, public/locales/nb/common.json, public/locales/nb/information.json, public/locales/nb/marketing.json, public/locales/nb/orders.json, public/locales/nb/wallet.json
More norwegian
Also  removes bookmarkWarning1 and bookmarkWarning2 from the english locale
=> Updated locale values

public/locales/nb/orders.json
Forgot we're only using on d for addresses
=> Fixes a typo

src/components/TokenSelect/TokenSelect.styles.tsx
I think this is what the issue asks for. 
https://user-images.githubusercontent.com/1560743/141177348-de0c394d-060f-4939-9614-daac91529133.mp4
Closes #354
=> Makes quote values have a text cursor on mouseover

src/components/Overlay/Overlay.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/WalletProviderList/WalletProviderList.tsx
Fixes small animation hick-up after connecting wallet. Fixes #340
=> 340: Fixed connect wallet animation

src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/subcomponents/ActionButtons/ActionButtons.tsx
=> Don't show track button if transactions tab open

src/components/TransactionsTab/TransactionsTab.styles.tsx, src/components/TransactionsTab/TransactionsTab.tsx
=> Close transaction drawer with wallet button

src/components/TokenSelect/TokenSelect.styles.tsx, src/components/TokenSelect/TokenSelect.tsx
=> Make token icon clickable

src/App.tsx, src/components/ProgressBar/ProgressBar.styles.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/SwapWidget/InfoSection.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/TransactionsTab/TransactionsTab.tsx, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.styles.tsx, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.tsx, src/components/WalletProviderList/WalletProviderList.tsx, src/features/wallet/Wallet.tsx
Closes #321 
- adds progress bar
- adds the icon from the designs
- removes transaction link ([ref](https://discord.com/channels/590643190281928738/844220258386575371/908071460298457139))
=> Add progress bars to transactions with expiries

src/components/SwapWidget/SwapWidget.tsx, src/components/TransactionsTab/TransactionsTab.tsx
Also removed unused variable in SwapWidget
=> Adding missing variable that prevents the app from starting

src/components/SocialButtons/SocialButtons.tsx
Adds the FR telegram as requested by Mathieu
=> Add FR telegram

src/components/TemporaryMobileLanding/TemporaryMobileLanding.styles.tsx
`overflow-x`  adds a scrollbar 📜
=> superflous overflow removed

src/components/TransactionsTab/TransactionsTab.styles.tsx
=> 398: Added padding to TransactionsTab when overflow

src/components/SwapWidget/SwapWidget.styles.tsx, src/components/Toasts/Toast.styles.tsx, src/components/Toasts/TransactionToast.tsx
Fixes #419 
Also fixed text size and padding of toast
=> 419: Fixed toast colors in light mode

src/components/TransactionsTab/TransactionsTab.styles.tsx, src/components/TransactionsTab/TransactionsTab.tsx
Fixes #421 
Also fixes scrollbar not behaving properly.
=> 421: Fixed transactions list height

src/styled-components/Link/Link.styles.tsx
=> 352: Changed visited link color style

src/components/SwapWidget/InfoSection.styles.tsx
=> 355: Price rate switch button color

src/components/IconButton/IconButton.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/Toolbar/Toolbar.styles.tsx, src/components/Toolbar/Toolbar.tsx, src/features/orders/ordersSlice.ts, src/style/mixins.ts
Closes #293 
- Turned airswap logo into reset button
- Added resetOrders action in orders store
=> 293: Added reset button

src/components/Page/Page.tsx, src/components/SwapWidget/subcomponents/SwapInputs/SwapInputs.styles.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/WidgetFrame/WidgetFrame.styles.tsx, src/components/WidgetFrame/WidgetFrame.tsx, src/style/styled.d.ts, src/style/themes.ts
Fixes #298 
Suggestions are welcome!
https://user-images.githubusercontent.com/86911296/142711717-aa914326-c54a-4718-8cf0-0728a3192fff.mov
https://user-images.githubusercontent.com/86911296/142713698-60d45f59-0473-4570-8cde-741040b3e7c7.mov
=> 298: Added connect wallet transition

public/locales/zh/translation.json, src/components/InformationModals/subcomponents/GuideButton/GuideButton.styles.tsx, src/components/TokenList/TokenList.styles.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/Toolbar/subcomponents/ToolbarButton/ToolbarButton.styles.tsx, src/helpers/isActiveLanguageLogographic.ts
Closes #437 
Added a `isActiveLanguageLogographic` helper for tweaking smaller font sizes which won't work well with chinese based languages.
=> 437: Added language specific styling

src/components/Page/Page.styles.tsx, src/components/Toolbar/Toolbar.styles.tsx, src/components/Toolbar/subcomponents/ToolbarButton/ToolbarButton.styles.tsx, src/style/sizes.ts
https://user-images.githubusercontent.com/86911296/147672995-930c7e2f-68d8-4f2c-85f7-ad7eb18894c7.mov
=> Added responsive style to Toolbar

public/locales/en/translation.json
#373 Corrected the wrong text for signer balance low under validator errors.
=> Corrected text for signer balance low

public/sitemap.xml, src/App.tsx
Since browserRouter does not work on github pages!
=> Restored HashRouter, modified sitemap

public/sitemap.xml, public/whitepaper.htm, src/App.tsx
=> adds title and meta description tags to /whitepaper.html

src/components/TokenList/TokenList.styles.tsx, src/components/TokenList/TokenList.tsx
=> 512: Fixed TokenList scroll when 6 tokens in list

package.json, src/helpers/findEthOrTokenByAddress.ts, yarn.lock
=> 522: fixed transactions list bug

src/components/TokenList/subcomponents/TokenButton/TokenButton.styles.tsx, src/components/TokenList/subcomponents/TokenImportButton/TokenImportButton.styles.tsx
=> 532: Fixed TokenImportButton styling on light mode

src/components/Page/Page.styles.tsx, src/components/SocialButtons/SocialButtons.styles.tsx, src/components/SocialButtons/SocialButtons.tsx, src/components/Toolbar/Toolbar.styles.tsx, src/components/Toolbar/Toolbar.tsx, src/components/Toolbar/subcomponents/ToolbarButton/ToolbarButton.styles.tsx
=> 463: Added social buttons to mobile menu

src/components/Overlay/Overlay.tsx, src/components/Page/Page.tsx, src/components/TransactionsTab/TransactionsTab.tsx, src/hooks/useKeyPress.ts
Fixes #564 
Pressing esc closes mobile menu and overlay now.
=> 564: Pressing esc closes mobile menu

src/components/Toolbar/Toolbar.tsx
This way we can release with all the new fixes and features in develop.
=> Remove OTC routes temporarily for main release

src/components/SwapWidget/SwapWidget.tsx
Fixes #622 
@dmosites Was not able to test on BSV chain. But this should fix it.
=> 622: Added library to Swap check parameters in SwapWidget

src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/helpers/index.ts, src/components/OrderDetailWidget/hooks/useOrderStatus.tsx, src/components/OrderDetailWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/features/takeOtc/takeOtcActions.ts, src/features/takeOtc/takeOtcHelpers.ts
- added getOrderStatus hook
- added getTakenState which calls NonceUsed
- currently only displays status if user is on correct chain, other wise shows open state (library errors otherwise)
=> Feature/617 Taken State from Nonce Used

src/components/MakeWidget/MakeWidget.tsx, src/components/TransactionsTab/helpers/getTimeAgoTranslation.spec.ts, src/contexts/lastLook/LastLook.tsx, src/features/metadata/metadataApi.ts, src/features/metadata/metadataSlice.ts, src/features/pricing/pricingApi.ts, src/features/pricing/pricingSlice.ts, src/features/wallet/Wallet.tsx
Fixes #375 
Also deleted tests that failed today, probably because today is 25 hours instead of 24.
=> 375: Get protocol fee from contract

src/components/Dropdown/Dropdown.styles.tsx, src/components/ExpiryIndicator/ExpiryIndicator.styles.tsx, src/components/ExpiryIndicator/ExpiryIndicator.tsx
Fixes #644 #645 
- color fixes for expiry and dropdown
- lowered transition delay on dropdown menu (0.3s -> 0.2s)
=> Fixes #644 & #645 OTC style fixes

src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/Toolbar/Toolbar.tsx
=> 643: Fixed make link

src/components/Dropdown/Dropdown.styles.tsx
=> 660: Fixed dropdown styling

src/components/ExpiryIndicator/helpers/index.ts, src/components/MyOrdersWidget/subcomponents/Order/Order.tsx
=> Fixes #651 Order Expiry format

src/components/MakeWidget/MakeWidget.tsx, src/components/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/SwapInputs/SwapInputs.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/TokenSelect/TokenSelect.tsx, src/helpers/getTokenMaxAmount.ts, src/hooks/useMaxAmount.ts
Fixes #674 
Fixes #675 
https://user-images.githubusercontent.com/86911296/202849061-68d21cee-5a8e-4e8b-b7da-a69f5ebb87f3.mov
One thing I noticed is that we round the amount with `stringToSignificantDecimals` so sometimes you're left with some dust amount which is a little annoying.
Also stumbled upon a bug with toAtomicString when trying to submit this dust amount. Created issue here:
https://github.com/airswap/airswap-protocols/issues/933
Edit: This error is intentional but we need to fix this in the interface.
=> 675: Added max button to maker widget

CONTRIBUTING.md, README.md, src/components/TransactionsTab/helpers/getTimeAgoTranslation.spec.ts, src/features/orders/ordersSlice.spec.ts
Fixes #685 
Also fixed some small linter warnings.
=> 685: Updated README and CONTRIBUTING

src/components/Button/Button.styles.tsx, src/components/Dropdown/Dropdown.styles.tsx, src/components/MakeWidget/subcomponents/ActionButtons/ActionButtons.styles.tsx, src/components/MakeWidget/subcomponents/ExpirySelector/ExpirySelector.styles.tsx, src/styled-components/Pill/Pill.tsx, src/styled-components/Select/Select.tsx
Fixes #682 
For some reason firefox alignment of the font is different than the other browsers. Could not figure out a more constructive solution than these firefox specific styling fixes on certain elements.
=> 682: Added firefox alignment fixes

src/components/MakeWidget/MakeWidget.styles.tsx, src/components/MakeWidget/MakeWidget.tsx, src/components/MakeWidget/subcomponents/AddressInput/AddressInput.styles.tsx, src/components/MakeWidget/subcomponents/AddressInput/AddressInput.tsx, src/components/SwapInputs/subcomponents/Tooltip/Tooltip.styles.tsx, src/features/makeOtc/makeOtcSlice.ts
=> Added tooltip and focus ring when address is invalid

src/components/ExpiryIndicator/ExpiryIndicator.tsx, src/components/ExpiryIndicator/helpers/index.ts, src/components/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/OrderDetailWidget/hooks/useOrderStatus.tsx
=> 699: Expiry Indicator needs to update itself every minute

src/components/TokenSelect/TokenSelect.styles.tsx
The solution I found was to Increase the font size to separate the dot from 'i'.
=> Firefox on windows icon not showing properly

src/features/transactions/transactionUtils.ts, src/features/transactions/useSwapLogs.ts
=> 739: Fixed Swap bug in useSwapLogs

src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/hooks/useTakerTokenInfo.tsx, src/components/SwapInputs/SwapInputs.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/components/TokenSelect/TokenSelect.tsx, src/constants/rpcUrls.ts, src/helpers/getRpcUrl.ts
Fixes #740 
https://user-images.githubusercontent.com/86911296/226141601-c0399ef6-3fdd-43dc-b60a-ae00756c30e3.mov
=> 740: Added fallback and loading state to custom tokens when wallet is not connected

src/components/AvailableOrdersWidget/AvailableOrdersWidget.tsx, src/components/AvailableOrdersWidget/helpers/getSortedIndexerOrders.ts, src/components/AvailableOrdersWidget/subcomponents/AvailableOrdersList/AvailableOrdersList.tsx, src/components/AvailableOrdersWidget/subcomponents/Order/Order.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/subcomponents/InfoButtons/InfoButtons.tsx, src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/subcomponents/InfoSection/InfoSection.styles.tsx, src/components/SwapWidget/subcomponents/InfoSection/InfoSection.tsx, src/constants/configParams.ts
- Move View All Quotes button to Swap screen
- integrate `bestSwapOption` into returned orders list
- remove access to available orders from OTC screens
=> Indexer On Swap Screen

package.json, src/components/SwapWidget/SwapWidget.tsx, src/features/indexer/indexerSlice.ts, yarn.lock
Upgrades to latest airswap packages.
Completed RFQ and OTC swaps on Goerli.
=> Packages upgrade

src/components/MakeWidget/MakeWidget.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/hooks/useSessionOrderTransaction.ts, src/components/OrderDetailWidget/subcomponents/OrderSubmittedInfo/OrderSubmittedInfo.styles.tsx, src/components/OrderDetailWidget/subcomponents/OrderSubmittedInfo/OrderSubmittedInfo.tsx, src/components/ReviewApprovalInfo/ReviewApprovalInfo.tsx
Fixes #766 
Also added fix for approval amount not checking for fee.
=> 766: Added fix for ReviewApprovalInfo and approve token

.env, src/components/CancelWidget/CancelWidget.tsx, src/components/LoadingSpinner/LoadingSpinner.styles.tsx, src/components/LoadingSpinner/LoadingSpinner.tsx, src/components/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/hooks/useOrderStatus.tsx, src/components/OrderDetailWidget/subcomponents/OrderDetailWidgetHeader/OrderDetailWidgetHeader.tsx, src/components/OrderDetailWidget/subcomponents/OrderStatusInfo/OrderStatusInfo.styles.tsx, src/components/OrderDetailWidget/subcomponents/OrderStatusInfo/OrderStatusInfo.tsx, src/hooks/useDefaultLibrary.ts
Fixes #767 
Also added a loading state while the contract function is called.
https://github.com/airswap/airswap-web/assets/86911296/5db3d206-7bc3-4496-8f5f-af17c86fa49b
=> 767: Fix order status for unconnected wallet

src/components/MakeWidget/MakeWidget.tsx, src/components/SwapInputs/SwapInputs.styles.tsx, src/components/SwapInputs/SwapInputs.tsx, src/components/SwapWidget/SwapWidget.tsx
Fixes #772 
https://github.com/airswap/airswap-web/assets/86911296/af2c2e00-45b0-41a6-a3a4-afcfbb92809f
Added to both MakeWidget and SwapWidget
=> 772: Added switch tokens button to SwapInputs

public/locales/en/translation.json, src/components/AvailableOrdersWidget/AvailableOrdersWidget.tsx, src/components/AvailableOrdersWidget/subcomponents/AvailableOrdersList/AvailableOrdersList.tsx, src/components/AvailableOrdersWidget/subcomponents/Order/Order.tsx, src/components/OrderDetailWidget/OrderDetailWidget.tsx, src/components/OrderDetailWidget/subcomponents/InfoButtons/InfoButtons.tsx, src/components/Overlay/Overlay.tsx, src/components/SwapWidget/SwapWidget.tsx, src/features/indexer/indexerSlice.ts, src/features/orders/ordersSlice.ts
- addresses all issues from feedback in https://github.com/airswap/airswap-web/pull/755 
- uses redux to handle searchAmount state with correct cleanup
- adds AvailableSwapsWidget to OrderDetailWidget as well for smoother transitions
* all server querying is the same, however, "Aggregate Error" can happen when re-querying. Not sure if this will be fixed by Mitsi and Whatdays current work etc. but lets please tackle this in another PR.
=> fix/751 OTC Swap Flow

src/components/MakeWidget/subcomponents/ActionButtons/ActionButtons.tsx
Fixes #795 
Solution:
https://github.com/airswap/airswap-web/assets/86911296/7d0a86ae-e04c-4369-bb20-6e5c72051a45
=> 795: Fixed user not being able to go back to review in MakeWidget

src/hooks/useValidAddress.ts
=> 800: Fixed useValidAddress not working on Linea

src/components/MakeWidget/MakeWidget.styles.tsx, src/components/MakeWidget/subcomponents/AddressInput/AddressInput.styles.tsx, src/components/MakeWidget/subcomponents/OrderReviewToken/OrderReviewToken.styles.tsx, src/components/MakeWidget/subcomponents/RateField/RateField.styles.tsx, src/components/MakeWidget/subcomponents/RateField/RateField.tsx
Fixes #794 
Moved alignment issues to #803
=> 794: Fixed some styling issues

public/locales/en/translation.json, src/components/TransactionLink/TransactionLink.tsx, src/components/TransactionsTab/subcomponents/WalletTransaction/WalletTransaction.tsx
Fixes #807 
https://github.com/airswap/airswap-web/assets/86911296/dd1ebc81-eda5-4438-8423-90495f59166b
=> 807: Fixed transaction link in WalletTransaction

package.json, src/constants/nativeCurrency.ts, src/constants/rpcUrls.ts, src/constants/supportedNetworks.ts, src/constants/supportedWalletProviders.ts, yarn.lock
Only ether and wrapped ether until their bridge is fully enabled.
=> Linea Mainnet Support

src/components/SwapWidget/SwapWidget.tsx
https://github.com/airswap/airswap-web/assets/90465420/3ae9975b-4dc8-4788-ad20-fc3644d3fa86
=> Fix/114 - SwapWidget: after completing a swap the allowance is not updated

src/components/SwapWidget/SwapWidget.tsx, src/components/SwapWidget/hooks/useBestTradeOptionTransaction.ts
=> 830: Fixed numeric fault error in swap widget

src/components/TokenList/subcomponents/TokenButton/TokenButton.styles.tsx
=> 826: Fixed TokenButton styling

src/components/SwapWidget/subcomponents/SwapWidgetHeader/SwapWidgetHeader.styles.tsx, src/components/SwapWidget/subcomponents/SwapWidgetHeader/SwapWidgetHeader.tsx, src/components/Timer/Timer.styles.tsx, src/components/Timer/Timer.tsx
Fixes #825 
https://github.com/airswap/airswap-web/assets/86911296/51db8d9d-4540-41e5-a4a5-bb0712aa40b4
=> 825: Added mono font to Timer

src/components/SwapInputs/SwapInputs.styles.tsx, src/components/TokenSelect/TokenSelect.tsx
=> 832: Fixed ETH tooltip glitching out

package.json, src/features/transactions/swapEventSubscriber.ts, yarn.lock
Upgrades libraries and metadata to 4.1 with respective change to how SwapERC20 events are handled.
=> SwapERC20 Upgrade

src/components/@widgets/SwapWidget/SwapWidget.tsx
=> 851: Added fix for bug when clicking restart in RFQ

src/hooks/useShouldDepositNativeTokenAmount.ts
=> 861: Fixed single quote in useShouldDepositNativeTokenAmount bug

src/components/@widgets/MakeWidget/MakeWidget.tsx, src/hooks/useInsufficientBalance.ts
=> 870: Added deductProtocolFee to useInsufficientBalance

src/components/@widgets/SwapWidget/SwapWidget.tsx
=> 872: Fixed user unable to complete unwrap WETH to ETH in RFQ

src/components/@widgets/SwapWidget/SwapWidget.tsx, src/features/metadata/metadataSubscriber.ts, src/features/transactions/useHistoricalTransactions.ts
=> 852: Fixed loading transactions from localStorage

src/components/@reviewScreens/ApproveReview/ApproveReview.tsx, src/components/@reviewScreens/TakeOrderReview/TakeOrderReview.tsx, src/components/@reviewScreens/WrapReview/WrapReview.tsx, src/components/@widgets/OrderDetailWidget/OrderDetailWidget.tsx, src/components/@widgets/SwapWidget/SwapWidget.tsx
=> 868: Cleanup of ErrorList in review screens

src/components/@widgets/OrderDetailWidget/OrderDetailWidget.tsx
=> 903: OTC order not reset properly

src/components/@widgets/SwapWidget/SwapWidget.tsx, src/entities/SubmittedTransaction/SubmittedTransactionHelpers.ts, src/features/quotes/hooks/useQuotesDebug.ts, src/features/quotes/quotesHooks.ts, src/features/transactions/helpers/getOrdersFromLogs.ts, src/features/transactions/helpers/getOrdersFromWrappedEventLogs.ts, src/features/transactions/hooks/useHistoricalTransactions.ts, src/features/transactions/hooks/useLatestSwapFromEvents.ts, src/features/transactions/transactionsHooks.ts, src/helpers/getOrdersFromLogs.ts, src/hooks/useSwapType.ts, src/types/swapType.ts
=> 906: Fix Swap with wrap functionality

src/helpers/getContractEvents.spec.ts, src/helpers/getContractEvents.ts
=> 918: Fix block limit error when traversing logs

src/components/Routes/Routes.tsx, src/components/TransactionsTab/TransactionsTab.styles.tsx, src/components/TransactionsTab/TransactionsTab.tsx, src/features/balances/balancesHooks.ts, src/features/balances/balancesSlice.ts, src/features/gasCost/gasCostSlice.ts, src/features/metadata/metadataActions.ts, src/features/metadata/metadataSlice.ts, src/features/myOrders/myOrdersHooks.ts, src/features/myOrders/myOrdersSlice.ts, src/features/orders/ordersSlice.ts, src/features/registry/registrySlice.ts, src/features/transactions/transactionsSlice.ts, src/features/wallet/Wallet.tsx, src/features/web3/web3Actions.ts, src/features/web3/web3Hooks.ts, src/features/web3/web3Slice.ts
=> 920: Clear data after wallet changes or disconnect

src/components/@widgets/SwapWidget/SwapWidget.tsx, src/features/quotes/quotesHooks.ts, src/features/wallet/Wallet.tsx
Fixes #909 
Was not able to fix LastLook not working on gnosis, so I'll disable it for now.
=> 909: Disabled LastLook when provider is gnosis

src/components/@widgets/MakeWidget/MakeWidget.tsx, src/entities/Server/ServerService.ts, src/features/makeOtc/makeOtcActions.ts, yarn.lock
Fixes #933 
No more hiccup after creating order.
https://github.com/airswap/airswap-web/assets/86911296/dd77bceb-2083-4494-a886-9cdd7be42669
=> 933: Added fix for laggy response when making order

src/features/balances/balancesHooks.ts, src/features/metadata/metadataHooks.ts
Fixes #935 
https://github.com/airswap/airswap-web/assets/86911296/dc95152e-7990-43fe-9a08-c40fdf5a192d
=> 935: Added fix for token balance not loading after import

src/components/TokenList/TokenList.tsx, src/features/metadata/metadataActions.ts, src/features/metadata/metadataHooks.ts, src/features/metadata/metadataSlice.ts, src/features/registry/registryActions.ts, src/features/web3/web3Slice.ts
=> 938: Active tokens are now filtered by chainId

src/components/@widgets/MakeWidget/subcomponents/RateField/RateField.tsx
=> 940: Fixed RateField reverse rate bug

src/components/@widgets/OrderDetailWidget/hooks/useTakerTokenInfo.tsx, src/features/metadata/metadataSlice.ts
Fix order detail not working for unconnected wallet.
=> Order detail fix for unconnected wallet

public/locales/en/translation.json, src/components/@widgets/MyOrdersWidget/MyOrdersWidget.styles.tsx, src/components/@widgets/MyOrdersWidget/MyOrdersWidget.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/ActionButtons/ActionButtons.styles.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/InfoSection/InfoSection.styles.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/InfoSection/InfoSection.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/MyOrdersList/MyOrdersList.styles.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/MyOrdersList/MyOrdersList.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/MyOrdersListSortButtons/MyOrdersListSortButtons.styles.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/MyOrdersListSortButtons/MyOrdersListSortButtons.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/Order/Order.styles.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/SortButton/SortButton.styles.tsx, src/components/Typography/Typography.styles.tsx, src/hooks/useElementSize.ts, src/hooks/useIsOverflowing.ts, src/pages/MyOrders/MyOrders.styles.tsx, src/pages/MyOrders/MyOrders.tsx, src/style/sizes.ts
=> OTC orders list

src/components/@widgets/MakeWidget/MakeWidget.styles.tsx, src/components/@widgets/MakeWidget/MakeWidget.tsx, src/components/@widgets/MakeWidget/subcomponents/AddressInput/AddressInput.styles.tsx, src/components/@widgets/MakeWidget/subcomponents/ExpirySelector/ExpirySelector.styles.tsx, src/components/@widgets/MakeWidget/subcomponents/OrderTypeSelector/OrderTypeSelector.styles.tsx, src/components/@widgets/MakeWidget/subcomponents/OrderTypeSelector/OrderTypeSelector.tsx, src/components/Dropdown/Dropdown.styles.tsx, src/components/TokenSelect/TokenSelect.styles.tsx, src/style/mixins.ts, src/style/sizes.ts, src/styled-components/Select/Select.tsx
Fixes #971 
https://github.com/user-attachments/assets/82f89b14-01c1-4232-ae9e-5613156b31e1
=> 971: Added redesign to Make widget

src/styled-components/BorderedButton/BorderedButton.tsx
Fixes #973 
https://github.com/user-attachments/assets/35d0870d-8c86-425f-b29b-02336f7276b3
=> 973: Added new glow animation to BorderedButton

src/components/ErrorList/ErrorList.styles.tsx, src/components/ErrorList/ErrorList.tsx, src/components/ErrorList/subcomponents/ErrorListItem/ErrorListItem.styles.tsx
=> 969: Added redesign for error list

src/components/@widgets/OrderDetailWidget/hooks/useTakerTokenInfo.tsx, src/components/TokenSelect/TokenSelect.styles.tsx
=> WIP: 937: Added fix for unknown tokens balance bug

src/components/@widgets/MakeWidget/MakeWidget.tsx, src/components/@widgets/MakeWidget/helpers/index.ts, src/components/@widgets/MakeWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/@widgets/OrderDetailWidget/OrderDetailWidget.tsx, src/components/@widgets/OrderDetailWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/@widgets/SwapWidget/SwapWidget.styles.tsx, src/components/@widgets/SwapWidget/SwapWidget.tsx, src/components/@widgets/SwapWidget/subcomponents/ActionButtons/ActionButtons.tsx, src/components/Button/Button.tsx, src/features/web3/web3Hooks.ts, src/features/web3/web3Slice.ts, src/hooks/useBalanceLoading.ts
Fixes #985 
https://github.com/user-attachments/assets/d4387a3e-3a7b-405d-a493-ab1d274b77d8
=> Fix loading state when connecting / switching wallet

src/features/quotes/quotesHooks.ts, src/hooks/useBalanceLoading.ts
=> Fix for RFQ order fetch bug

public/locales/en/translation.json, src/components/@widgets/MakeWidget/MakeWidget.tsx, src/components/@widgets/OrderDetailWidget/OrderDetailWidget.tsx, src/components/@widgets/SwapWidget/SwapWidget.tsx, src/components/ApprovalSubmittedScreen/ApprovalSubmittedScreen.tsx, src/components/DepositSubmittedScreen/DepositSubmittedScreen.tsx, src/components/OrderSubmittedScreen/OrderSubmittedScreen.tsx, src/components/OverlayLoader/OverlayLoader.styles.tsx, src/components/OverlayLoader/OverlayLoader.tsx, src/components/WalletSignScreen/WalletSignScreen.tsx, src/features/transactions/transactionsSlice.ts, src/hooks/useDepositPending.ts, src/styled-components/Overlay/Overlay.tsx
Fixes #983 
https://github.com/user-attachments/assets/1687d45d-ccb7-4e3a-89eb-5cfd5207c089
=> 983: Submitted Deposit overlay

public/locales/en/translation.json, src/components/@widgets/CancelWidget/CancelWidget.tsx, src/components/@widgets/CancelWidget/subcomponentss/SubmittedCancellationScreen/SubmittedCancellationScreen.tsx, src/components/OrderSubmittedScreen/OrderSubmittedScreen.styles.tsx, src/hooks/useCancellationPending.ts, src/hooks/useDepositPending.ts
Fixes #982 
https://github.com/user-attachments/assets/f771ad2b-5e6e-4a62-9a51-db64b3d1810a
=> 982: Added transaction overlay to cancel widget

src/features/balances/balancesHooks.ts
=> 1007: Repeat swaps doesn’t decrement approval amounts

package.json, src/entities/ExtendedPricing/ExtendedPricingService.ts, src/features/indexer/indexerHelpers.ts, src/features/indexer/indexerRegistryApi.ts, src/features/orders/ordersActions.ts, src/features/quotes/quotesActions.ts, src/features/quotes/quotesApi.ts, src/features/transactions/hooks/useLatestApproveFromEvents.ts, src/features/transactions/hooks/useLatestTransaction.ts, yarn.lock
=> Upgrade to 5.0.9 @airswap/libraries

src/components/@widgets/CancelWidget/CancelWidget.tsx, src/components/@widgets/MyOrdersWidget/MyOrdersWidget.tsx, src/components/SubmittedCancellationScreen.tsx
=> 963: Sign and cancel order screen on my orders page

src/components/@widgets/MyOrdersWidget/subcomponents/Order/Order.styles.tsx, src/components/@widgets/MyOrdersWidget/subcomponents/Order/Order.tsx, src/components/@widgets/SwapWidget/SwapWidget.tsx
=> 1011: Fix for available orders screen bug

src/features/makeOtc/makeOtcActions.ts, src/pages/OrderDetail/OrderDetail.tsx
=> 1017: OTC ens address fix

src/app/store.ts
=> 1015: Fixed dispatch type warning
